trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: |
      sudo apt-get install apt-transport-https
      sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
    displayName: 'Setup sdk'
  - script: |
      sudo apt-get update
      sudo apt-get install dart
    displayName: 'Install sdk'
  - script: 
      /usr/lib/dart/bin/pub get 
    displayName: 'Pub get'    
  - script: 
      /usr/lib/dart/bin/pub run test ./test/all_test.dart --platform vm
    displayName: 'Unit test'
  - script: 
      /usr/lib/dart/bin/pub global activate dart_coveralls 
    displayName: 'activate coverall'
  - script: 
      /usr/lib/dart/bin/pub global run dart_coveralls report ./test/all_test.dart
    displayName: 'report coverage'
