name: DelugeDartParser
description: Deluge lang parser in dart.
# version: 0.0.1
# homepage: https://gurudhanush.github.io
# author: Guru 

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  petitparser: ^2.4.0
  graphs: ^0.2.0
  json_rpc_2: ^2.1.0
  logging: ^0.11.3+2
  tuple: ^1.0.2
  quiver: ^2.0.5
  just_debounce_it: ^3.0.0+1
  yaml: ^2.1.16
  path: ^1.6.4
  benchmark_harness: ^1.0.5




dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0


executables:  
  DelugeDartParser: main

